### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by BB9z** [RFUI/RFAPI#1]
### Beta3

- [ ] Retry?
- [ ] Download task
- [ ] Auto uploading/downloading HUD
- [ ] More tests
- [ ] UIViewController APIControl?

### Beta2

- [x] Build-in control bind
- [x] Error localization
- [x] Usage guide

### Beta1

- [x] AFNetworking 3
- [x] New callback mechanism
- [x] Sent request with define
- [x] Test
- [x] Support multi JSON lib
- [x] Cache?
- [x] Support macOS
